package-lock.json, package.json, src/components/AltitudeGraph.vue, src/components/AltitudeGraphPlot.vue, src/components/PlotFigure.ts, src/components/TheActivity.vue, src/router/index.ts, src/views/AltitudeGraph.vue
=> Sample Elevation or Altitude Graph

src/components/ElevationGraphPlot.vue
=> Update Elevation Graph

src/components/ElevationGraphD3.vue, src/components/ElevationGraphPlot.vue
=> Elevation Graph Update

src/components/ElevationGraphPlot.vue, src/components/TheActivity.vue, src/components/TheMap.vue
=> sync elevation graph on show marker to show pop up at map

src/components/ElevationGraphPlot.vue, src/components/TheActivity.vue, src/components/TheMap.vue, src/toolkit/date.ts, src/toolkit/distance.ts
=> Elevation Graph Enhance

src/components/ElevationGraphPlot.vue, src/components/TheActivity.vue, src/components/TheNavigator.vue, src/toolkit/date.ts
- TheActivity now uses Option over composition
- Fix minor bug on displaying created date
- Fix yMin on map to scale automatically based on min altitude
- Lint date.ts
=> fix: ensure consistency and minor bugfix

index.html, package-lock.json, package.json, src/assets/bootstrap.scss, src/assets/main.scss, src/components/AreaGraph.vue, src/components/ElevationGraph.vue, src/components/OpenActivity.vue, src/components/PowerGraph.vue, src/components/TheActivity.vue, src/components/TheLap.vue, src/components/TheLoading.vue, src/components/TheMap.vue, src/components/TheNavigator.vue, src/components/TheSession.vue, src/components/TheSummary.vue, src/main.ts, src/router/index.ts, src/spec/activity.ts, src/toolkit/date.ts, src/views/OpenActivityView.vue, src/wasm/fitsvc/activity/activity.go, src/wasm/fitsvc/activity/listener.go, src/wasm/fitsvc/activity/service.go, src/wasm/fitsvc/go.mod, src/wasm/fitsvc/go.sum
fix:
- ui/ux: add tab analysis, sessions, laps, tools
- distance calculation on multiple fit files
routing:
- / ->  /legacy
- /v0 -> /
=> fix: ui/ux, distance calculation on combined record

src/assets/scrollbar.scss, src/components/OpenActivity.vue, src/components/TheMap.vue, src/components/legacy/TheActivity.vue
- cluster size 10% of records per session. 1 session = 10 features.
- est. ~10x faster lookup than previous algorithm (was searching whole records)
=> feat: clustering map features for fast lookup

src/components/TheMap.vue
=> feat: add route-line outline color

src/components/OpenActivity.vue, src/spec/activity.ts, src/wasm/activity-service/activity/fit/listener.go, src/wasm/activity-service/activity/fit/session.go, src/wasm/activity-service/activity/gpx/service.go, src/wasm/activity-service/activity/session.go, src/wasm/activity-service/activity/tcx/service.go, src/wasm/activity-service/activity/util.go
- These sport ["", "Other", "All"]  will be treated as "Generic" sport
- Mark multi-sport "Transition" to have Pace calculated.
=> fix: standarize sports

src/components/AreaGraph.vue, src/components/CadenceGraph.vue, src/components/ElevationGraph.vue, src/components/HeartRateGraph.vue, src/components/OpenActivity.vue, src/components/PaceGraph.vue, src/components/PowerGraph.vue, src/components/SpeedGraph.vue, src/components/TemperatureGraph.vue, src/components/TheMap.vue
https://github.com/openivity/openivity.github.io/assets/3763178/c9b9d30e-a204-46cf-94aa-cfba781c4335
=> All Chart Freeze Marker on Pointer Down (unfreeze on pointer down again)

src/components/OpenActivity.vue, src/wasm/activity-service/service/result.go, src/wasm/activity-service/service/service.go
- Add how long it takes to serialize the result to help us better understanding the performance of our current WASM implementation.
=> chore: add serialization elapsed and total elapsed

src/components/AreaGraph.vue, src/components/OpenActivity.vue
- enable graph by timestamp when there is no distance, e.g. indoor training.
- fix glitch on graph hover due to `svg` translate based on pure pointer position, changed to `nearestRecord`, this is noticeable when the records is small, for most cases this is barely noticeable.
Before:
https://github.com/openivity/openivity.github.io/assets/15964188/2d57e6ad-59da-4480-84a6-619ae37a0c91
After:
https://github.com/openivity/openivity.github.io/assets/15964188/d3869f27-129d-467d-9a1c-66185b2fd3e6
=> feat: enable graph by timestamp when there is no distance

src/App.vue, src/assets/bootstrap.scss, src/components/HeartRateZoneBar.vue, src/components/OpenActivity.vue, src/components/SplitPaceGraph.vue, src/toolkit/activity.ts, vite.config.ts
- ~~Auto-select Split by option based total distance (try to make fewest option with minimum 7-10 option)~~
=> Feat. Splits Pace Graph

src/spec/activity-service.ts, src/spec/activity.ts, src/wasm/activity-service/activity/fit/service.go, src/wasm/activity-service/activity/gpx/service.go, src/wasm/activity-service/activity/session.go, src/wasm/activity-service/activity/tcx/service.go, src/wasm/activity-service/activity/util.go, src/wasm/activity-service/preprocessor/preprocessor.go, src/wasm/activity-service/service/result/sport_list.go, src/wasm/activity-service/service/service.go, src/workers/activity-service.ts
=> feat: add WorkoutType field in Session, and ToleranceMovingSpeed in Sport

src/components/SplitPaceGraph.vue
Split pace with some invalid record:
Split pace with multiple session (mixed sport)
=> Split pace last data invalid with invalid record + Support Multisession

src/components/ToolModeSelector.vue, src/wasm/activity-service/activity/fit/listener.go, src/wasm/activity-service/activity/fit/session.go, src/wasm/activity-service/service/service.go
=> fix (#55): combine activity should combine last session and first session of the corresponding activities

src/components/AreaGraph.vue, src/components/ElevationGraph.vue
=> fix (#73): handling null altitude, instead of treat as 0, make it minDomain

.github/workflows/main.yml, docs/CONTRIBUTING.md
chore: update branch info in CONTRIBUTING.md
=> chore: change release build using master branch

src/wasm/activity-service/activity/session.go
=> fix: new session from laps missing sport

src/components/OpenActivity.vue, src/components/TheNavigatorInput.vue, src/wasm/activity-service/activity/activity.go, src/wasm/activity-service/activity/fit/fit.go, src/wasm/activity-service/activity/session.go, src/wasm/activity-service/go.mod, src/wasm/activity-service/go.sum, src/wasm/activity-service/manufacturers.json, src/wasm/activity-service/service/service.go
Can be merge after #117 is merged.
=> Merge 'dev' into 'master'

vite.config.ts
Discussion: https://github.com/openivity/openivity.github.io/discussions/122#discussion-7275993
=> fix: pwa enable cleanupOutdatedCaches

src/wasm/activity-service/service/service.go
- Fix bug on wrong conceal and trim marker
=> Release 28-10-2024

src/components/ToolFieldsRemover.vue
- Enable distance and speed removal, the use case for this is when cadence/speed sensors calculate wrong distance and speed, by removing these fields from activity file, we can make openivity recalculate them for us next time we open the activity file. In the WASM-side, it's already implemented, this only enable the feature flag
- Simplify code on checking field exist.
=> feat: enable distance and speed removal
