src/components/OpenActivity.vue
src/components/TheSummary.vue
src/wasm/activity-service/activity/fit/lap.go
src/wasm/activity-service/activity/fit/listener.go
src/wasm/activity-service/activity/fit/service.go
src/wasm/activity-service/activity/gpx/service.go
src/wasm/activity-service/activity/lap.go
src/wasm/activity-service/activity/service.go
src/wasm/activity-service/activity/session.go
src/wasm/activity-service/activity/tcx/service.go
src/wasm/activity-service/activity/util.go
src/wasm/activity-service/kit/kit.go
src/wasm/activity-service/preprocessor/preprocessor.go

- [WASM] fit service now handle irregular encoded records where some values of the same timestamp spread into multiple records. 
Irregular records found in Strava's exported `Fit file` that was recorded directly from Strava mobile app, and exported from web like this (Export Original):
- [WASM] fit service now fill missing value in `lap` and `session` with our service calculation.
- [WASM] fix pace calculation: if speed is present, convert speed into pace rather than manually calculating from distance and elapsed.
- [FE] summarizeRecords now handle missing distance and treat them as 0 to avoid NaN value causing graph can't be rendered.
- [FE] summary now return time elapsed with correct time gap calculation

fix: fit service logic

---

src/wasm/activity-service/activity/tcx/record.go
src/wasm/activity-service/activity/tcx/schema/activity.go
src/wasm/activity-service/activity/tcx/schema/author.go
src/wasm/activity-service/activity/tcx/schema/lap.go
src/wasm/activity-service/activity/tcx/schema/tcx.go
src/wasm/activity-service/activity/tcx/schema/track.go

TCX:
- fix: tcx decode unexpected error due to improper HR parse handling
- add TrackpointExtension for Speed
- verbose error handling

fix: tcx decode unexpected error due to improper HR parse handling

---

package-lock.json
package.json
vite.config.ts

npm i vite-plugin-pwa -D
The cache strategies ref: https://developer.chrome.com/docs/workbox/caching-strategies-overview/
OSM tiles included to be cached:
Assets are all in precache, and osm tiles in runtime cache

feat: add PWA (Servicer Worker) to enable offline processing

---

src/components/HeartRateZoneBar.vue

- Safari for iphone mini:
- Firefox for macOS

fix: hr-zone label alignment

---

src/components/HeartRateZoneGraph.vue

Ignore Invalid HR on HR Zone

---

src/wasm/activity-service/activity/lap.go

With previous algorithm, when we have these following records pattern, these records will be skipped entirely
```go
records[0].altitude = 100
records[1].altitude = nil
records[2].altitude = 101
records[3].altitude = nil
records[4].altitude = 102
records[5].altitude = nil
```
Previous algorithm: 
- When the `i = 0 and i+1 = 1`, we skipped the calculation, then `i = 1 and i+1 = 2`, we also skipped it again.
To mitigate this records pattern, we need to compare it to the next non-nil value, then move the cursor to that next record.

fix: total ascent/descent and total elapsed/moving time calculation

---

src/components/SplitPaceGraph.vue

- fix descent calculation missed use subtract instead sum.
- rename ascent/descent variable.
- update compare altitude with latest previous valid altitude (instead previous), so this will support null altitude on jumped record.

Fix bug split pace elevation calculation

---

src/components/AreaGraph.vue
src/components/TheLap.vue
src/components/TheSession.vue

if default collapse content is showing 
on collapse content
- add class `show` & `collapse`
we add on collapse
- add class `collapsible`
and on caret-right
- add class `collapse-indicator`
if default collapse content is not-showing
on collapse content
- add class `collapse`
we add on collapse
- add class `collapsible` & `collapsed`
and on caret-right
- add class `collapse-indicator`

Apply caret model style to all modules

---

src/components/ToolTrackpointsSlider.vue
src/wasm/activity-service/activity/fit/service.go

fix (#62): tool's trim/conceal negative distance

---

src/wasm/activity-service/go.mod
src/wasm/activity-service/go.sum

Changes that might affect this app:
- Garmin has release SDK version `21.126` on Nov 21 2023 with additional manufacturer and garmin product list, this new FIT SDK for Go version v0.2.0 have been sync with that changes.
- Fix on handling invalid values on float32 and float64 types.
Release notes: 
- https://github.com/muktihari/fit/releases/tag/v0.1.6
- https://github.com/muktihari/fit/releases/tag/v0.2.0

chore: bump FIT SDK for Go version from v0.1.5 to v0.2.0

---

src/wasm/activity-service/activity/fit/service.go
src/wasm/activity-service/activity/session.go

- TotalCalories was not calculated in Session that was created from Laps
- For FIT files that have no laps at all, we should create it from session so we do not lose any information, for example total calories only available in session and lap but not in records,  we can't aggregate the value from records. (Note: 1 Session should at least have 1 Lap)

fix(no-ticket): missing information in lap and session

---

src/wasm/activity-service/go.mod
src/wasm/activity-service/go.sum

chore: bump fit sdk version from 0.2.0 to 0.3.1

---

src/wasm/activity-service/activity/tcx/service.go

The device mapping for tcx should be taken from:
`TCX Root -> Activities -> Activity -> Creator -> Name`.
Not 
`TCX Root -> Author -> Name`

fix(no ticket): device mapping for tcx

---

src/wasm/activity-service/go.mod
src/wasm/activity-service/go.sum

- Minor fix on sorting timestamp for `Course` and `Set` messages since these legacy messages have different `timestamp_id`, most activity files don't have these messages but just in case.

chore: bump fit sdk version from v0.19.0 into v0.19.1

---

.github/workflows/build-test.yml
.github/workflows/main.yml

- Build WebAssembly using latest version of Go. Go promise: "Old Go code will always run on newer version". This way we will always get the best version of Go with latest security patch.
- Bump Node version from v18 to v20 since version 18 will be deprecated next year. I use Node v20 locally, our code run just fine.

chore: update workflow

---

src/wasm/activity-service/service/service.go

When FIT files contains SplitSummary messages, the combined FIT file could not be uploaded to Garmin Connect. The workaround is to not including SplitSummary messages from the next FIT files.

fix: combined FIT file is unable to be uploaded to Garmin Connect

---

src/components/ToolDeviceSelector.vue
src/wasm/activity-service/go.mod
src/wasm/activity-service/go.sum

- When user changes the deviceName manually (text input), we will try to match deviceName from user's input into our database so we can get a valid `manufacturerId` and `ProductId` in case user wants to export to FIT later, however we do not specify a fallback when the mapping value is not found, for GPX and TCX only the deviceName is required.
- This is not related to the issue, but let's just include it: bump `xmltokenizer` to `v0.0.2`
Let's do patch release after this 😅

fix: export GPX and TCX wrong DeviceName

---

src/wasm/activity-service/.gitignore
src/wasm/activity-service/activity/lap.go
src/wasm/activity-service/activity/preprocessor.go
src/wasm/activity-service/activity/record.go
src/wasm/activity-service/activity/session.go

Some manufacturers may prefer using enhanced fields rather than ordinary field. For example, using EnhancedAltitude over Altitude. Since we were only using Altitude, the altitude data in some FIT files (one of which was produced by Garmin devices) could not be displayed properly. This applies for other enhanced field such as EnhancedSpeed, EnhancedAvgSpeed, etc.

fix: allow enhanced fields

---

src/wasm/activity-service/activity/activity.go
src/wasm/activity-service/activity/fit/fit.go
src/wasm/activity-service/go.mod
src/wasm/activity-service/go.sum
src/wasm/activity-service/service/service.go

- Previously, we discard split summary messages since we didn't how to properly combine it since if combine it incorrectly, the resulting file will be rejected by Garmin Connect. Now we know that this message should be unique for each split_type.
- Bump FIT SDK for Go to latest version.

Enhance: Update SDK and support split summary messages

---

src/wasm/activity-service/manufacturers.json

Sources:
- Suunto: https://aspartnercontent.blob.core.windows.net/apizone/docs/DeviceProductIDs.pdf
- Bryton: typically use first 4 digits of UUID, it's shown on the app (it's perhaps the year and month of release), so we can get the ID by watching youtube on people connect their devices 😂

feat: add product ids mapping

---

src/wasm/activity-service/go.mod
src/wasm/activity-service/go.sum

Previous version of FIT SDK for Go has bug on component expansion logic, see https://github.com/muktihari/fit/pull/474 for details.

bump FIT SDK for Go version to latest

---

src/wasm/activity-service/service/service.go

When the user does not specify the conceal or trim parameters, the default markers are `0` for `startN` and `len(Records)-1` for `endN`. 
Previously, the service concealed records at the start position `<= startN` and at the end position `>= endN`, which resulted in the first and last records always being concealed. It should have been set to `< startN` and `> endN`. 
Some platforms, such as Runkeeper, will reject a GPX file if its `<trkpt>` elements do not include the `lat` and `lon` attributes, even for a single record.
This kind of issue can be minimized when we fully implement unit tests tracked on #94, but I haven't have time yet.

fix: wrong conceal or trim marker

---

src/wasm/activity-service/activity/fit/fit.go
src/wasm/activity-service/activity/session.go

Currently, aggregator does not work if the struct has embedded struct/pointer, need to aggregate it directly.
I found this issue when trimming an activity and found out that some of session's fields are missing.

fix: aggregate session from laps
